name: Generate RSS Feed

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y php-curl

      - name: Generate RSS feed
        run: |
          mkdir -p output
          echo "Fetching content from https://www.tanea.gr/allnews"
          curl -L -o output/rss-feed.xml https://www.tanea.gr/allnews
          echo "RSS feed generated and saved to output/rss-feed.xml"
          ls -l output

      - name: Commit and push RSS feed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output/rss-feed.xml
          git commit -m 'Generate RSS feed'
          git push

